DROP TABLE IF EXISTS product_parameter_values CASCADE;

DROP TABLE IF EXISTS parameters CASCADE;

DROP TABLE IF EXISTS parameter_groups CASCADE;

DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS images CASCADE;

DROP TABLE IF EXISTS brands CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS invoice CASCADE;

DROP TABLE IF EXISTS invoice_items CASCADE;